### ISSUE TITLE
Input for Flip/None

### ISSUE THREAD

**Issue by JustinTrotter** [YeahHmm/Conniption#6]
Issue:
Entering nothing when prompted to flip or not does not move the turn to the next player, allowing a player multiple moves.

Example:
Player A: 4 flips remaining
input action (flip/none): [empty string]

Player A: 4 flips remaining
input action (place [1-7]): 7

Player A: 4 flips remaining
input action (flip/none): [empty string]

Player A: 4 flips remaining
input action (flip/none): [empty string]

Solution:
At this point it's still Player A's turn. Entering an empty string should be the same as typing 'none'

**Comment by akgunter** [comment]
I think this is a problem with main() in main.py, which is rather minimally coded right now. That function is going to evolve as we build the infrastructure, and hopefully the issue will resolve itself. We could also fix it right now, but we'll end up rewriting main() regardless.
